### ISSUE TITLE
configure: cannot create config.log: is a directory

### ISSUE THREAD

**Issue by wtchappell** [madworx/docker-netbsd#18]
I can't seem to use the image to build anything using autotools; when trying either an in-tree or out-of-tree build of either `ruby` or `libarchive` I get the following error:

```
configure: cannot create config.log: is a directory
```

If I check, it is indeed a directory for some reason. More interestingly, I cannot remove it:

```
bash-5.0# rm -rf config.log
rm: config.log: Stale NFS file handle
```

I suspect I'm getting bitten by something with the nfsroot setup, but I'm not sure how to debug further.

**Comment by wtchappell** [comment]
I've managed to work around the issue by mounting a UFS filesystem from a qcow2 image and doing my work on that - which works fairly well. It'd still be better to have the full NFS root approach working though - since adding a static filesystem to the Docker image bloats the size a fair bit.

**Comment by madworx** [comment]
Interesting - thanks for the report, @wtchappell!

With recent versions of the Linux kernel I've seen some issues with unfsd hanging at 100% CPU (due to a bug in unfsd), which I patched and built new docker images for.

Which version of NetBSD are you using, and are you building your own Docker image or using the madworx/netbsd stock ones?

**Comment by wtchappell** [comment]
That makes sense, I figured it'd be something like that.

I believe I've hit this with both `8.1` from DockerHub and with a `9.0` I built myself from the repo here.

For at the former I was using `FROM madworx/netbsd:8.1-x86_64`. I'll get you a Docker image that sets up an environment where you can see the error sometime today/tonight.

**Comment by wtchappell** [comment]
Very strange; I was able to reliably replicate this but can't anymore. If I hit it again I'll make sure I have a working test case before reopening this.

Sorry to bother, and thanks for the image!

**Comment by madworx** [comment]
Thank you for the report -- I'm always interested in knowing if something's awry. :-)

If it pops up again, please reopen this ticket or start a new one.

Out of curiosity -- have you been able to use KVM acceleration for the image? On my end, for the past six months or so the NetBSD kernel hangs upon boot -- I'm suspecting this is due to changed behaviour in the host operating system.

**Comment by wtchappell** [comment]
I suspect this may be back based on the reappearance of some issues writing out `+INSTALLED_INFO` files during the `pkg_add` step of the Docker build process, but I'm not sure - the version of this container I'm using has moved to doing work in a `tmpfs` instead, which helps with the slow speed of virtualization as well. I'm guessing it'll disappear as soon as I try to confirm it again...

In terms of KVM acceleration - yes! I've been using KVM acceleration with some success and I've been meaning to open another PR to the README about it. My host system is an Arch Linux x86_64 machine, if that's interesting.
